### PR TITLE
Add Korean locale

### PR DESCRIPTION
**Pull request by blood72**
I knew today that there was a good program.
I recommended this program to people around me.
I translated it to make it easier to use for them.

### CODE REVIEW

**Comment by alyssaxuu** [comment]
Amazing, thank you so much! Would it be possible to also translate the Chrome Store description so I can publish it there & merge? :) https://chrome.google.com/webstore/detail/screenity-screen-recorder/kbbdabhdfibnancpjfhlkhafgdilcnji?hl=en

**Comment by blood72** [comment]
Oh it's an honor for me too.
I don't know how to provide it there, but I'll put the translation here.

```
Chrome 확장 중 가장 강력한 화면 녹화 프로그램. 캡쳐, 주석달기, 수정, 그 외.
Screenity와 함께라면 이전과는 다르게 녹화하고 화면에 필기할 수 있습니다. 상황에 맞는 피드백을 주고 학생들에게 자세한 설명과 단순히 잠재 고객에게 제품을 보여주면서 작업, 교육 등 녹화물을 더 좋게 만드세요.

특징
🎥 탭, 데스크탑, 응용 프로그램 및 카메라 무제한 녹화
✏️ 화면 어떤 곳이든지 그림 그리기, 텍스트 추가 및 화살표 긋기
👀 녹화 중에 마우스 클릭 강조, 마우스 포커싱 또는 마우스 숨기기
🎙️ 개별 마이크 및 컴퓨터 오디오 컨트롤, 눌러서 말하기 등
⚙️ 맞춤형 카운트다운, 커서를 갖다댈 때만 컨트롤을 표시하고 기타 여러 커스터마이징할 수 있는 옵션들 제공
💾 mp4, gif, webm 형식으로 내보내거나 Google Drive에 직접 저장
✂️ 녹화한 내용 자르기 및 일부 영역 제거
...그리고 더 많이 - 이 모든게 무료 & 로그인도 필요없이!

Screenity가 왜 다른 화면 녹화 프로그램과 비교했을 때 가장 강력한 지 확인해보세요 👉  https://docs.google.com/spreadsheets/d/1juc1zWC2QBxYqlhpDZZUNHl3P6Tens6YiChchFcEJVw/edit?usp=sharing

자체호스팅 또는 Screenity에 새로운 기능을 추가하거나 자신만의 화면 녹화 프로그램을 만들고 싶으세요? GitHub에 있는 코드를 확인해보세요! 👉 https://github.com/alyssaxuu/screenity

Screenity는 Alyssa X에 의해 빌드 및 유지관리됩니다. (https://alyssax.com)
```

**Comment by alyssaxuu** [comment]
Just merged + will go live in the Chrome Store in a couple of hours :) Thanks again - I'll give you credit in the README if that's okay.

**Comment by alyssaxuu** [comment]
Went live just now in the version 2.4.2 if you want to check it out! https://chrome.google.com/webstore/detail/screenity-screen-recorder/kbbdabhdfibnancpjfhlkhafgdilcnji?hl=ko

**Comment by blood72** [comment]
Wow! Thank you so much!

**Pull request merged**
