### PR TITLE
add Chinese language

### PR DESCRIPTION
**Pull request by xkonglong**

### CODE REVIEW

**Comment by alyssaxuu** [comment]
Amazing thank you!! @xkonglong do you think you could translate the Chrome Store description so I can publish it there? I can also give you credit if that's okay (don't think Google Translate will do a good job...)

"The most powerful screen recorder for Chrome. Capture, annotate, edit, and more.
With Screenity you can record and annotate your screen like never before. Make better recordings for work, education, and more, giving contextual feedback, detailed explanations to your students, or simply showcasing your product to potential customers.

FEATURES
🎥 Make unlimited recordings of your tab, desktop, any application, and camera
✏️ Annotate by drawing anywhere on the screen, adding text, and creating arrows
👀 Highlight your clicks, focus on your mouse, or hide it from the recording
🎙️ Individual microphone and computer audio controls, push to talk, and more
⚙️ Custom countdowns, show controls only on hover, and many other customization options
💾 Export as mp4, gif, and webm, or save the video directly to Google Drive
✂️ Trim or remove sections of your recording
...and much more - all for free & no sign in needed!

Compare Screenity with other screen recorders and see why it's the most powerful one out there 👉  https://docs.google.com/spreadsheets/d/1juc1zWC2QBxYqlhpDZZUNHl3P6Tens6YiChchFcEJVw/edit?usp=sharing

Want to self-host, add new features to Screenity, or even make your own screen recorder? Feel free to check out the code on GitHub! 👉 https://github.com/alyssaxuu/screenity

Screenity is built and maintained by Alyssa X (https://alyssax.com)"

**Comment by xkonglong** [comment]
@xkonglong<https://github.com/xkonglong> do you think you could translate the Chrome Store description so I can publish it there? I can also give you credit if that's okay (don't think Google Translate will do a good job...)

OK, This is the translation  for you want :

“
Chrome 上最强大的屏幕录像机, 可以录屏，标注，编辑等。
借助 Screenity，您可以前所未有地录制和标注屏幕, 更好地录制工作、教育等内容，为学生提供情景反馈、详细的解释，或者只是向潜在客户展示您的产品。

特点
🎥 无限制的录制您的标签页、桌面、任何应用程序和摄像头
✏️ 在屏幕任意位置绘画、添加文本和箭头进行标注
👀 高亮您的点击，聚焦您的鼠标，或者在录制时隐藏
🎙️ 单独的麦克风和电脑音频控制，一键通（PTT）等
⚙️ 可定义倒计时，悬停时显示控制栏，以及更多自定义选项
💾 导出为 mp4,、gif 和 webm，也可以保存视频到谷歌云盘
✂️ 对您的录制做修剪或者移除片段
……还有更多，所有功能都免费，且无需登录！

将 Screenity 与其他屏幕录制工具比较，看看为什么它才是最强大的👉
https://docs.google.com/spreadsheets/d/1juc1zWC2QBxYqlhpDZZUNHl3P6Tens6YiChchFcEJVw/edit?usp=sharing

想要自主管理，给 Screenity 添加新功能，甚至制作自己的录屏工具？
随时在 Github 上检查代码！👉 https://github.com/alyssaxuu/screenity

Screenity 由 Alyssa X (https://alyssax.com) 建立和维护。

”



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Alyssa X<mailto:notifications@github.com>
发送时间: 2020年12月16日 15:32
收件人: alyssaxuu/screenity<mailto:screenity@noreply.github.com>
抄送: 小恐龙<mailto:lhgtop@gmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [alyssaxuu/screenity] add Chinese language (#38)


Amazing thank you!! @xkonglong<https://github.com/xkonglong> do you think you could translate the Chrome Store description so I can publish it there? I can also give you credit if that's okay (don't think Google Translate will do a good job...)

"The most powerful screen recorder for Chrome. Capture, annotate, edit, and more.
With Screenity you can record and annotate your screen like never before. Make better recordings for work, education, and more, giving contextual feedback, detailed explanations to your students, or simply showcasing your product to potential customers.

FEATURES
🎥 Make unlimited recordings of your tab, desktop, any application, and camera
✏️ Annotate by drawing anywhere on the screen, adding text, and creating arrows
👀 Highlight your clicks, focus on your mouse, or hide it from the recording
🎙️ Individual microphone and computer audio controls, push to talk, and more
⚙️ Custom countdowns, show controls only on hover, and many other customization options
💾 Export as mp4, gif, and webm, or save the video directly to Google Drive
✂️ Trim or remove sections of your recording
...and much more - all for free & no sign in needed!

Compare Screenity with other screen recorders and see why it's the most powerful one out there 👉 https://docs.google.com/spreadsheets/d/1juc1zWC2QBxYqlhpDZZUNHl3P6Tens6YiChchFcEJVw/edit?usp=sharing

Want to self-host, add new features to Screenity, or even make your own screen recorder? Feel free to check out the code on GitHub! 👉 https://github.com/alyssaxuu/screenity

Screenity is built and maintained by Alyssa X (https://alyssax.com)"

**Comment by alyssaxuu** [comment]
Great, I merged the changes and it's going to go live on the 2.4.3 version in the Chrome Store, I think in a couple of hours :) I also gave you credit in the README.

**Comment by xkonglong** [comment]
Great !

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Alyssa X<mailto:notifications@github.com>
发送时间: 2020年12月16日 16:18
收件人: alyssaxuu/screenity<mailto:screenity@noreply.github.com>
抄送: 小恐龙<mailto:lhgtop@gmail.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [alyssaxuu/screenity] add Chinese language (#38)


Great, I merged the changes and it's going to go live on the 2.4.3 version in the Chrome Store, I think in a couple of hours :) I also gave you credit in the README.

―

**Comment by blinovartem** [comment]
@alyssaxuu have you already sent the release to the store? If not, please wait, I will prepare another language

**Comment by alyssaxuu** [comment]
> @alyssaxuu have you already sent the release to the store? If not, please wait, I will prepare another language

The new version with Chinese just went live. Feel free to translate into another language and I will make a new version ^^

**Pull request merged**
