### PR TITLE
Updated 'Self-hosting Screenity' section of README.md and Translations improvement (pt_BR and pt_PT)

### PR DESCRIPTION
**Pull request by erickvils**
New instruction #5 with procedures to generate OAuth Client ID necessary to enable the Google Drive Upload (authorization consent screen).

### CODE REVIEW

**Review by briankim12 — COMMENTED** [review]
This is a great fix! Much needed for self hosting

**Review by briankim12 — APPROVED** [review]
Please

**Comment by briankim12** [comment]
Hello, I am having a very hard time running the extension locally through developer mode. I managed to fix one error regarding to Google OAuth thanks to this post; however, I'm getting other errors regarding
image

**Comment by alyssaxuu** [comment]
> Hello, I am having a very hard time running the extension locally through developer mode. I managed to fix one error regarding to Google OAuth thanks to this post; however, I'm getting other errors regarding image

Hmm, and it's not working at all? I do get the last 2 errors but they don't affect the extension (mostly to do with permissions and where the extension is allowed to run). I am not aware of the 3rd one or the first two though, do you have the Chrome Store version of Screenity installed while running the self hosted one? Have you tried reloading the extension?

You might also need to set a key in the manifest.json, I believe it is not necessary as per [this](https://developer.chrome.com/docs/extensions/mv3/manifest/key/), but it could be causing issues with the Google Drive integration. You can create one by following the steps in that page. I will update the README if that's what's causing the issue.

**Comment by briankim12** [comment]
> > Hello, I am having a very hard time running the extension locally through developer mode. I managed to fix one error regarding to Google OAuth thanks to this post; however, I'm getting other errors regarding image
> 
> Hmm, and it's not working at all? I do get the last 2 errors but they don't affect the extension (mostly to do with permissions and where the extension is allowed to run). I am not aware of the 3rd one or the first two though, do you have the Chrome Store version of Screenity installed while running the self hosted one? Have you tried reloading the extension?
> 
> You might also need to set a key in the manifest.json, I believe it is not necessary as per [this](https://developer.chrome.com/docs/extensions/mv3/manifest/key/), but it could be causing issues with the Google Drive integration. You can create one by following the steps in that page. I will update the README if that's what's causing the issue.

The extension is working fine actually. So I just wanted to make it clear. 
I followed all the instructions about running it locally including updating the OATH. 
Also, I deleted the   "key": "EXTENSION_KEY" part of the manifest. Am I supposed to be doing this or replacing with another value? If don't delete it right now, it does not let me unpack the extension.

**Pull request merged**
